### ISSUE TITLE
Initialization without key/iv hashing

### ISSUE THREAD

**Issue by Anexen** [magiclen/rust-magiccrypt#13]
Hi, thank you for the library. I appreciate its simple and intuitive interface. 
However, I came across an unexpected implementation detail: the key/iv values are hashed when initializing the MagicCrypt struct. Because of this, I was unable to decrypt existing values that were created earlier (and not [just](https://github.com/magiclen/rust-magiccrypt/issues/11) [me](https://stackoverflow.com/questions/65332716/how-to-encrypt-with-cryptojs-and-decrypt-with-rust-magic-crypt)). Since I cannot modify the old algorithm, I had to implement the decryption function myself using low-level libraries.

Is there a way to avoid using hashing when initializing MagicCrypt? I can send a PR.
I see two possible solutions:
1. something like fallible `new_unhashed` function.
2. new default feature that enables hashing and optional md5 and sha256 crates.

**Comment by magiclen** [comment]
MagicCrypt is implemented not only in the Rust languages but also in other programming languages such as Java, PHP, JavaScript/Node.js. It is used for encrypting any data and decrypting the data which is encrypted by MagicCrypt. If your existing values are not encrypted by MagicCrypt, you should use other cryptography libraries.

**Comment by Anexen** [comment]
I understand that the library is not implemented only for Rust, so I propose a compatible solution.
I believe that the decryption of existing values is a useful functionality for many users, as there is no library for other languages (e.g., Python), or an algorithm without hashing is already in use (e.g., raw PostgreSQL encryption functions).
If you are not interested in making the library useful for more users, please feel free to close the issue.
