### ISSUE TITLE
Not producing the same result as c#

### ISSUE THREAD

**Issue by last-Programmer** [magiclen/rust-magiccrypt#2]
Please check this .net fiddle

[https://dotnetfiddle.net/5i95oJ](https://dotnetfiddle.net/5i95oJ)

i wrote this rust using your library

```rust
#[macro_use] extern crate magic_crypt;

use magic_crypt::{MagicCrypt};

fn main() {

    let mut mc: MagicCrypt = new_magic_crypt!("12345678", 64, "12345678");
    let base64 = mc.encrypt_str_to_base64("Balu");
    println!("{}", base64);
}
```

It does not produce the same result as c#. Can you help me in fixing this with rust?

Thanks in Advance

**Comment by magiclen** [comment]
I don't know much about c#. But for AES/DES encryption, you need to decide a padding mode (such as PKCS#5) and a cipher mode (such as CBC, ECB) and an IV (initialization vector) if it is needed which I didn't see in your C# code.

**Comment by last-Programmer** [comment]
i am using IV in the c# code. could you please tell me what is the default mode used in magic crypt and how to change it so that i use the same mode in both. in c# the default mode is cbc and the default padding mode is pkcs7. please let me know how to specify these things with magic crypt

**Comment by magiclen** [comment]
MagicCrypt uses PKCS#5 (or PKCS#7 with 128-bit blocks) and CBC block cipher mode. The string of key is hashed by CRC-64/WE (for DES), MD5 (for AES-128), TIGER192-3 (for AES-192) or SHA256 (for AES-256). The string of IV is hashed by CRC-64/WE.

**Comment by last-Programmer** [comment]
It seems to be that key and iv is not hashed in c#. So i tried removing hashing in your code for key and iv and the result does not match. any idea why the results are not same?

**Comment by magiclen** [comment]
Please paste your Rust code.

**Comment by last-Programmer** [comment]
Here is the code

```rust
use block_modes::block_padding::Pkcs7;
use block_modes::{BlockMode, Cbc};
use des::Des;

type DesCbc = Cbc<Des, Pkcs7>;

macro_rules! get_des_cipher_space {
    ($len:expr) => {{
        (($len + 8) / 8) * 8 + ($len % 8)
    }};
}

fn main() {

    let key =  b"12345678";
    let iv = b"12345678";
    let data = b"Balu";
    let len = data.len();
    let final_len = get_des_cipher_space!(len);
    let mut buffer = Vec::with_capacity(final_len);
    unsafe {
        buffer.set_len(final_len);
    }
    buffer[..len].copy_from_slice(data);
    let cipher = DesCbc::new_var(key, iv).unwrap();
    let enc = base64::encode(&cipher.encrypt_vec(&buffer[..len]));
    println!("{:?}", enc);
}
```

**Comment by last-Programmer** [comment]
The issue is resolved. There was a problem in .net fiddle It is adding newline character to the string which is encrypted.
