### ISSUE TITLE
Replace rust-crypto dependency

### ISSUE THREAD

**Issue by igor-raits** [magiclen/rust-magiccrypt#3]
That one did not have release for 4 years and still depends on deprecated `gcc` crate, on very old version of `rand` and other dependencies too.

**Comment by igor-raits** [comment]
From what I see:

* md5 can be replaced with https://crates.io/crates/md-5
* sha256 can be replaced with https://crates.io/crates/sha2
* cbc_* can be replaced with https://crates.io/crates/block-modes

The other usages I am not really sure about.

**Comment by igor-raits** [comment]
@magiclen any chance you can work on this? I'm packaging https://gitlab.com/news-flash/news_flash_gtk for Fedora and this is blocking that effort.

**Comment by magiclen** [comment]
@ignatenkobrain A totally new version of this crate has been released. The `rust-crypto` crate has been removed.

**Comment by igor-raits** [comment]
@magiclen amazing, thank you! btw, I have sent PR to upgrade digest to https://gitlab.com/rawler/tiger/-/merge_requests/1 (I guess this is only one reason why you have digest-old dependency here).
