### ISSUE TITLE
digest 0.9.x update

### ISSUE THREAD

**Issue by igor-raits** [magiclen/rust-magiccrypt#5]
Hello,

Maintainer of magic-crypt in Fedora here. Would appreciate if you could update digest to 0.9 (along with all dependencies like des, aes-soft and such).

**Comment by magiclen** [comment]
The update has been done, though the `tiger-digest` crate still needs the old `digest` (^0.7.5) crate.

**Comment by magiclen** [comment]
The old `digest` crate has been removed.

6464943495f6f9505188ca1588d0118a632f46e4
