### ISSUE TITLE
Failed to fill the whole buffer.

### ISSUE THREAD

**Issue by Sagebati** [magiclen/rust-magiccrypt#8]
Updated to 3.1.4 from 2.1.10, and now I get this error `thread 'main' panicked at 'Couldn't decrypt the file: IOError(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })'` when trying to decrypt. 

The file is a random binary file generated by Okteta, it encrypted using  `let crypt = new_magic_crypt!(key, 256)`. 

Works with 2.1.10, this is a supposed regression.

**Comment by magiclen** [comment]
This bug occurred after version 3.1.0. It's been fixed now.

26aba9b25266d475e5e69e8229a8cfb7c83ba6a1
