### ISSUE TITLE
The key length is 56 bits is not supported

### ISSUE THREAD

**Issue by darkSuperman** [magiclen/rust-magiccrypt#9]
hi, I need to decrypt a file, but the file is decrypted with a 56-bit key length + IV, and I will get an error when I try to use 56 
` let mc = new_magic_crypt!("abcdefgh1234567",  56, "abcd1234"); `  
When I use 64：
` let mc = new_magic_crypt!("abcdefgh1234567",  64, "abcd1234"); ` 
Run will report an error：DecryptError(BlockModeError) 

How can i fix it, thanks

**Comment by magiclen** [comment]
MagicCrypt is used for encrypting any data and decrypting the data which is encrypted by MagicCrypt. You need to use another low-level cryptography library to decrypt your file.

**Comment by darkSuperman** [comment]
thanks
